name: Flatpak CI

on:
  push:
    branches:
    - master
    - flatpak-1.0.x
    - flatpak-1.2.x
    - flatpak-1.4.x
    - flatpak-1.6.x
    - flatpak-1.8.x
    - flatpak-1.10.x
    - flatpak-1.12.x
  pull_request:
    paths-ignore:
    - README.md
    - NEWS
    - INSTALL
    - COPYING
    - CODE_OF_CONDUCT.md
    - uncrustify.cfg
    - uncrustify.sh
    branches:
    - master
    - flatpak-1.0.x
    - flatpak-1.2.x
    - flatpak-1.4.x
    - flatpak-1.6.x
    - flatpak-1.8.x
    - flatpak-1.10.x
    - flatpak-1.12.x

jobs:
  check:
    name: Build with gcc and test
    runs-on: ubuntu-18.04
    steps:
    - name: Install Dependencies
      run: |
        sudo add-apt-repository ppa:alexlarsson/flatpak
        sudo add-apt-repository ppa:alexlarsson/glib260
        sudo add-apt-repository 'deb https://download.mono-project.com/repo/ubuntu stable-bionic main' # Needed for updates to work
        sudo apt-get update
        sudo apt-get install -y libglib2.0 attr automake gettext autopoint bison  dbus gtk-doc-tools \
        libfuse-dev ostree libostree-dev libarchive-dev libzstd-dev libcap-dev libattr1-dev libdw-dev libelf-dev python3-pyparsing \
        libjson-glib-dev shared-mime-info desktop-file-utils libpolkit-agent-1-dev libpolkit-gobject-1-dev \
        libseccomp-dev libsoup2.4-dev libsystemd-dev libxml2-utils libgpgme11-dev gobject-introspection \
        libgirepository1.0-dev libappstream-glib-dev libdconf-dev clang socat meson libdbus-1-dev e2fslibs-dev
        # One of the tests wants this
        sudo mkdir /tmp/flatpak-com.example.App-OwnedByRoot
    - name: Check out flatpak
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build malcontent dependency
      run: |
        git clone --branch 0.4.0 --depth 1 --no-tags https://gitlab.freedesktop.org/pwithnall/malcontent.git ./malcontent
        pushd ./malcontent
        meson setup --prefix=/usr _build
        ninja -C _build
        sudo ninja -C _build install
        popd
    - name: Create logs dir
      run: mkdir test-logs
    - name: autogen.sh
      run: NOCONFIGURE=1 ./autogen.sh
    - name: configure
      # TODO: Enable gtk-doc builds
      run: |
        mkdir _build
        pushd _build
        ../configure  --enable-internal-checks --enable-asan
        popd
      env:
        CFLAGS: -O2 -Wp,-D_FORTIFY_SOURCE=2
    - name: Build flatpak
      run: make -C _build -j $(getconf _NPROCESSORS_ONLN)
    - name: Run tests
      # TODO: Build with -j (currently ends up with hangs in the tests)
      run: make -C _build check
      env:
        ASAN_OPTIONS: detect_leaks=0 # Right now we're not fully clean, but this gets us use-after-free etc
    - name: Collect overall test logs on failure
      if: failure()
      run: mv _build/test-suite.log test-logs/ || true
    - name: Collect individual test logs on cancel
      if: failure() || cancelled()
      run: mv _build/tests/*.log test-logs/ || true
    - name: Upload test logs
      uses: actions/upload-artifact@v1
      if: failure() || cancelled()
      with:
        name: test logs
        path: test-logs

  clang:
    name: Build with clang and analyze
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp', 'python' ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python' ]
        # Learn more:
        # https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#changing-the-languages-that-are-analyzed
    steps:
    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
        # If you wish to specify custom queries, you can do so here or in a config file.
        # By default, queries listed here will override any specified in a config file.
        # Prefix the list here with "+" to use these queries and those in the config file.
        # queries: ./path/to/local/query, your-org/your-repo/queries@main
    - name: Install Dependencies
      run: |
        sudo add-apt-repository ppa:alexlarsson/flatpak
        sudo add-apt-repository ppa:alexlarsson/glib260
        sudo add-apt-repository 'deb https://download.mono-project.com/repo/ubuntu stable-bionic main' # Needed for updates to work
        sudo apt-get update
        sudo apt-get install -y libglib2.0 attr automake gettext autopoint bison  dbus gtk-doc-tools \
        libfuse-dev ostree libostree-dev libarchive-dev libzstd-dev libcap-dev libattr1-dev libdw-dev libelf-dev python3-pyparsing \
        libjson-glib-dev shared-mime-info desktop-file-utils libpolkit-agent-1-dev libpolkit-gobject-1-dev \
        libseccomp-dev libsoup2.4-dev libsystemd-dev libxml2-utils libgpgme11-dev gobject-introspection \
        libgirepository1.0-dev libappstream-glib-dev libdconf-dev clang e2fslibs-dev
    - name: Check out flatpak
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: configure
      run: ./autogen.sh  --enable-gtk-doc --enable-gtk-doc-html
      env:
        CC: clang
        CFLAGS: -Werror=unused-variable
    - name: Build flatpak
      run: make -j $(getconf _NPROCESSORS_ONLN)
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

  valgrind:
    name: Run tests in valgrind
    needs: check # Don't run expensive test if main check fails
    runs-on: ubuntu-20.04 # Might as well test with a different one too
    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo add-apt-repository 'deb https://download.mono-project.com/repo/ubuntu stable-focal main' # Needed for updates to work
        sudo apt-get install -y libglib2.0 attr automake gettext autopoint bison  dbus gtk-doc-tools \
        libfuse-dev ostree libostree-dev libarchive-dev libzstd-dev libcap-dev libattr1-dev libdw-dev libelf-dev python3-pyparsing \
        libjson-glib-dev shared-mime-info desktop-file-utils libpolkit-agent-1-dev libpolkit-gobject-1-dev \
        libseccomp-dev libsoup2.4-dev libsystemd-dev libxml2-utils libgpgme11-dev gobject-introspection \
        libgirepository1.0-dev libappstream-glib-dev libdconf-dev clang socat meson libdbus-1-dev \
        e2fslibs-dev
        sudo apt-get install -y autoconf automake autopoint autotools-dev binutils binutils-common binutils-x86-64-linux-gnu \
        build-essential cpp-8 debhelper dh-autoreconf dh-strip-nondeterminism docbook docbook-xsl dpkg-dev dwz g++ g++-9 gcc \
        gcc-8 gcc-8-base gcc-9 gcc-9-multilib gcc-multilib gettext gfortran-8 ibverbs-providers intltool-debian lib32asan5 \
        lib32atomic1 lib32gcc-9-dev lib32gcc-s1 lib32gomp1 lib32itm1 lib32quadmath0 lib32stdc++6 lib32ubsan1 \
        libarchive-zip-perl libasan5 libatomic1 libbinutils libc-dev-bin libc6-dev libc6-dev-i386 libc6-dev-x32 libc6-i386 \
        libc6-x32 libcroco3 libcrypt-dev libctf-nobfd0 libctf0 libdebhelper-perl libevent-core-2.1-7 libevent-dev \
        libevent-extra-2.1-7 libevent-openssl-2.1-7 libevent-pthreads-2.1-7 libfabric1 libfile-stripnondeterminism-perl \
        libgcc-8-dev libgcc-9-dev libgfortran-8-dev libgfortran5 libhwloc-dev libhwloc-plugins libhwloc15 libibverbs-dev \
        libibverbs1 libitm1 liblsan0 libltdl-dev libmpx2 libnl-3-dev libnl-route-3-dev libnuma-dev libopenmpi-dev libopenmpi3 \
        libpmix2 libpsm-infinipath1 libpsm2-2 libquadmath0 librdmacm1 libsigsegv2 libstdc++-9-dev libsub-override-perl libtool \
        libtsan0 libubsan1 libx32asan5 libx32atomic1 libx32gcc-9-dev libx32gcc-s1 libx32gomp1 libx32itm1 libx32quadmath0 \
        libx32stdc++6 libx32ubsan1 libxnvctrl0 linux-libc-dev m4 make mpi-default-dev ocl-icd-libopencl1 openmpi-bin \
        openmpi-common po-debconf xsltproc libc6-dbg libc6-dbg-i386-cross # valgrind build dependencies
    - name: Check out flatpak
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build valgrind # to avoid https://bugs.kde.org/show_bug.cgi?id=369029
      run: |
        git clone --branch VALGRIND_3_18_1 --depth 1 git://sourceware.org/git/valgrind.git ./valgrind
        pushd ./valgrind
        NOCONFIGURE=1 ./autogen.sh
        ./configure --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --sysconfdir=/etc --localstatedir=/var
        make -j $(getconf _NPROCESSORS_ONLN)
        sudo make install
        popd
    - name: Build ostree dependency
      run: |
        git clone --branch v2020.8 --depth 1 --no-tags https://github.com/ostreedev/ostree.git ./ostree
        pushd ./ostree
        ./autogen.sh --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --sysconfdir=/etc --localstatedir=/var
        make -j $(getconf _NPROCESSORS_ONLN)
        sudo make install
        popd
    - name: Create logs dir
      run: mkdir test-logs
    - name: autogen.sh
      run: NOCONFIGURE=1 ./autogen.sh
    - name: configure
      # TODO: Enable gtk-doc builds
      run: |
        mkdir _build
        pushd _build
        ../configure
        popd
      env:
        CFLAGS: -O2
    - name: Build flatpak
      run: make -C _build -j $(getconf _NPROCESSORS_ONLN)
    - name: Run tests
      run: make -C _build check
      env:
        FLATPAK_TESTS_VALGRIND: true
    - name: Collect overall test logs on failure
      if: failure()
      run: mv _build/test-suite.log test-logs/ || true
    - name: Collect individual test logs on cancel
      if: failure() || cancelled()
      run: mv _build/tests/*.log test-logs/ || true
    - name: Upload test logs
      uses: actions/upload-artifact@v1
      if: failure() || cancelled()
      with:
        name: test logs
        path: test-logs
